### ISSUE TITLE
"Blank" Output for Select Input Fields

### ISSUE THREAD

**Issue by jelleigh** [mProjectsCode/obsidian-meta-bind-plugin#99] opened 2023-06-20 08:45 UTC
Hello! Thank you for the work you've done on this amazing plugin!

Is there any plan to allow for "blank" outputs for the select input fields? In other words, by selecting a blank option, the metadata field's value will clear?  At the moment, if I have an inlineSelect input field and include option( ), it outputs " " instead of no text. Option() results in an error.  

This would be useful for dataview queries built off the metadata in the current and target note (e.g., WHERE contains(file.frontmatter.example_field,this.file.frontmatter.example_field).

**Comment by mProjectsCode** [comment] 2023-07-06 17:02
fixed in febaaae20e77ec4afbf4ca7cfe928831bf4e78c4

you can add `option(null)` to add a blank option to a select

**Closed by mProjectsCode** 2023-07-06 17:02 UTC
Labels: feature request

**Comment by CorvusPenn** [comment] 2026-07-25 05:44
Is `option(null)`'s intended behavior to display "null" as text in the drop down select?
It sets the YAML property to an empty state correctly, but I've been trying to find a way to be able to set the dropdown back to it's original blank state instead of displaying "null" as literal text.
If this is the intended behavior, I'll find an alternative solution, but if there's a way to accomplish what I'm looking for I'd like to know.
