### ISSUE TITLE
Append Templater Note into an existing Note

### ISSUE THREAD

**Issue by rycue** [mProjectsCode/obsidian-meta-bind-plugin#370] opened 2024-07-02 08:01 UTC
### Describe the Feature you'd Like

I wish there was a feature that allows me to append a **Templater note** to an existing note or to other existing notes using a button.

My request is similar to "templaterCreateNote" function, but it only creates a new note.

I hope this feature will be implemented as it would be a nice addition for easier automation to existing notes.

### Additional Context

Thank you so much for developing the best plugin.

**Comment by mProjectsCode** [comment] 2024-07-05 13:42
duplicate of #296

**Closed** 2024-07-05 13:42 UTC
Labels: duplicate, feature request
