### ISSUE TITLE
Extension makes mobile app unusable 

### ISSUE THREAD

**Issue by the1gofer** [mProjectsCode/obsidian-meta-bind-plugin#181] opened 2024-01-08 20:41 UTC
### Please fill out these Check-boxes

- [X] I checked that the plugin is up to date
- [X] The issue persist with all other plugins and themes disabled

### This Issue Occurs on

- [ ] Windows
- [ ] Linux
- [ ] macOS
- [X] Android
- [X] iOS

### Plugin Version

0.11

### Describe the Issue

Activating plugin and clicking buttons causes app crashes.  Both iOS and android. 

On iOS It will continue to crash untill can manage to get into the settings and disable it again.

fir android, it immediately crashes.  Do I can’t disable it.  I’m not sure how to get that working. 

### Steps to Reproduce

See above

### Expected Behavior

See anove

**Comment by mProjectsCode** [comment] 2024-01-08 20:52
Can you please provide reproduction steps? What kind of buttons are you talking about? Buttons created with the plugin?

**Comment by mProjectsCode** [comment] 2024-01-08 21:22
I just tested [buttons](https://www.moritzjung.dev/obsidian-meta-bind-plugin-docs/guides/buttons/) on my android device and I can't get it to crash.

**Comment by the1gofer** [comment] 2024-01-08 22:35
![07A61B0F-5645-4C2F-A960-C983D310B6D0_4_5005_c](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/2140724/b248263f-b5fc-43e2-ae7f-c93b0cb0e65b)

that's ios

**Comment by mProjectsCode** [comment] 2024-01-08 22:48
can you send me the note with the button that is causing the crash?

**Comment by the1gofer** [comment] 2024-01-08 22:52
[Dash.md](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/files/13866933/Dash.md)

**Comment by mProjectsCode** [comment] 2024-01-08 23:01
I can't reproduce the issue. Does this happen with all buttons or just specific ones? Does this happen on desktop as well?

**Comment by the1gofer** [comment] 2024-01-08 23:18
No, it's not happening on desktop macOS.  Do you know of a way to disable
the plugins without using the app?   At this point I can't really get far
enough to disable anything else to test.
Jason Crews

**Comment by mProjectsCode** [comment] 2024-01-08 23:28
you can try to start obsidian in restricted mode, but idk how to do that on iOS

**Comment by mProjectsCode** [comment] 2024-01-09 11:44
You issue might ber related to this https://github.com/mProjectsCode/obsidian-meta-bind-plugin/issues/102

**Comment by the1gofer** [comment] 2024-01-09 15:07
That does seem like it

Jason Crews

**Comment by mProjectsCode** [comment] 2024-01-15 00:45
I am going to close this as a duplicate of #102.

**Closed by mProjectsCode** 2024-01-15 00:45 UTC
Labels: bug, can't reproduce
