### ISSUE TITLE
Exclusions, please? 

### ISSUE THREAD

**Issue by thecookiemomma** [mProjectsCode/obsidian-meta-bind-plugin#111] opened 2023-08-06 00:46 UTC
**Is your feature request related to a problem? Please describe.**
With the advent of Obsidian 1.4ff, I have seen an issue in MB, and it may be a very rare use case.  I use Templater to help me in my templates so that the Properties manager doesn't pick up the frontmatter in templates. I do this so that the exceptions such as <% tp. file.ctime %> can be considered dates in the completed new file in the properties.  However, due to the automatic process of adding the metadata to the top of the file, my workflow for editing my templates has become *quickly delete the frontmatter that MB creates then close the file* when I am done fixing the file.  

**Describe the solution you'd like**
Please allow for exclusion of paths for automatic insert of the Metadata into the frontmatter.  For templates' sake.  

**Additional context**
As I say, this may be an edge case, but I can see it becoming more of a thing as more people get the 1.4.  Thank you for your consideration.

**Comment by mProjectsCode** [comment] 2023-08-06 11:44
Duplicate of https://github.com/mProjectsCode/obsidian-meta-bind-plugin/issues/81

**Comment by thecookiemomma** [comment] 2023-08-06 14:59
Sorry.  Didn't look first.

**Comment by mProjectsCode** [comment] 2023-09-22 18:50
Finally got it done and added some pictures of it in the other issue.

**Comment by mProjectsCode** [comment] 2023-10-04 22:52
Shipped in `0.6.0`

**Closed by mProjectsCode** 2023-10-04 22:52 UTC
Labels: duplicate, feature request
