### ISSUE TITLE
Multi Column support - Buttons don't work

### ISSUE THREAD

**Issue by LazyFridayStudio** [mProjectsCode/obsidian-meta-bind-plugin#208] opened 2024-02-05 11:43 UTC
### Please fill out these Check-boxes

- [X] I checked that the plugin is up to date
- [ ] The issue persist with all other plugins and themes disabled

### This Issue Occurs on

- [X] Windows
- [X] Linux
- [X] macOS
- [X] Android
- [ ] iOS

### Plugin Version

0.12.0

### Describe the Issue

The buttons themselves render, but when click the button nothing happens.

Have check that the buttons themselves work outside of the columns but only when inside they break.

# Plugin Link
https://github.com/ckRobinson/multi-column-markdown

### Steps to Reproduce

1. Install both plugins, https://github.com/ckRobinson/multi-column-markdown
2. create a multi column which consists of 2
3. Add a button that opens a URL or a note
4. Render in reading mode and button wont work.

### Expected Behavior

When clicking a button it will do as the open/command says

**Comment by mProjectsCode** [comment] 2024-02-05 12:35
Duplicate of #79 and #88.

**Closed** 2024-02-05 12:35 UTC
Labels: bug, duplicate, wontfix
