### ISSUE TITLE
Nested properties don't bind past the first level

### ISSUE THREAD

**Issue by miscoined** [mProjectsCode/obsidian-meta-bind-plugin#124] opened 2023-10-13 09:02 UTC
-   [x] The Plugin is up to date
-   [x] Obsidian is up to date

**Describe the bug**
Binding for nested properties doesn't appear to work if there are multiple levels of nesting.

**To Reproduce**
1. Make a note with the following contents

```
---
parent:
  child1:
    grandchild: 0
  child2: 0
---

`INPUT[number:parent.child1.grandchild]`
`INPUT[number:parent.child2]`
```
2. In Reading mode, try to change the value of both text fields
3. Observe that the first text field, bound to `parent.child1.grandchild` does not update the value of the metadata (while the second text field updates the value of `parent.child2`) as expected

**Expected behavior**
Nested field updates work regardless of depth

**Screenshots**
![Screenshot_2023-10-13_20-00-36](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/10219544/29b193ac-da58-457b-9575-222d0e16e963)

**Occurs on**

-   [ ] Windows
-   [ ] macOS
-   [x] Linux confirmed
-   [x] Android
-   [ ] iOS

(I suspect this happens regardless of OS)

**Plugin version**
0.6.5

**Comment by dbarenholz** [comment] 2023-10-25 12:29
I cannot reproduce this behaviour - it "just works" for me.

![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/25849034/b90e4b90-cb20-4f26-870e-6340f806fbfe)

Both for inline, as well for normal codeblocks, meta-bind accurately updates the YAML of the note.
For reference, my Obsidian debug information:
```
SYSTEM INFO:
	Obsidian version: v1.4.16
	Installer version: v1.4.13
	Operating system: Windows 10 Pro 10.0.22000
	Login status: not logged in
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 2
	Plugins enabled: 2
		1: Dataview v0.5.61
		2: Meta Bind Plugin v0.6.5

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

**Comment by dbarenholz** [comment] 2023-10-25 12:31
Note: it _also_ just works on my Android device. What's going on here? Do you have a typo in your metadata somewhere maybe?

**Comment by mProjectsCode** [comment] 2023-11-02 09:26
I also can't repro the issue, so i am going to close it for now. `0.7.0` made changes to that part of the code anyway.

**Closed by mProjectsCode** 2023-11-02 09:26 UTC
Labels: bug, can't reproduce
