### ISSUE TITLE
FAQ opens to blank page

### ISSUE THREAD

**Issue by ITMighty** [mProjectsCode/obsidian-meta-bind-plugin#243] opened 2024-03-04 21:10 UTC
### Please fill out these Check-boxes

- [X] I checked that the plugin is up to date
- [X] The issue persist with all other plugins and themes disabled

### This Issue Occurs on

- [X] Windows
- [ ] Linux
- [ ] macOS
- [ ] Android
- [ ] iOS

### Plugin Version

0.12.5

### Describe the Issue

Trying to open the FAQ page opens to a blank page. I saw there was a issue reported the other day, and closed soon after, stating that it was fixed, but it doesn't appear to be. I have updated Obsidian, the plugin, and ran a sandboxed vault with only this plugin enabled. I can confirm the issue persists regardless of the vault.

### Steps to Reproduce

1. Open Obsidian.
2. Make sure the plugin is enabled in **Community plugins**.
3. Select the _Meta Bind_ community plugin settings at the bottom of the plugin list.
4. Click the button **Open FAQ**.
5. Gaze into the abyss!

### Expected Behavior

The FAQ opens like it used to, showing little snippets of fields and such from the plugin docs.

**Comment by mProjectsCode** [comment] 2024-03-04 21:53
duplicate of #230

**Comment by mProjectsCode** [comment] 2024-03-04 21:54
I fixed it and will release the fix as part of `1.0.0`.

**Closed by mProjectsCode** 2024-03-04 21:54 UTC
Labels: bug

**Comment by ITMighty** [comment] 2024-03-05 14:27
Apologies, @mProjectsCode. I knew it was a duplicate of the closed bug report but the resolution of that report made it appear as though the current versions should have the FAQ fixed. Carry on and thanks for providing the work on this plugin. It's GREAT!!

(don't sue me, Kellogg's)
