### ISSUE TITLE
openNote view options

### ISSUE THREAD

**Issue by kevinkickback** [mProjectsCode/obsidian-meta-bind-plugin#282] opened 2024-04-06 21:56 UTC
### Is your Feature Request Related to a Problem?

When using "openNote: true" in templaterCreateNote button the newly created note always opens in the current tab/leaf and always in editor mode.

### Describe the Feature you'd Like

Have the option to open note in new leaf/tab and/or select the default mode the note will open in (editor/reading).

### Additional Context

Thank you for all your hard work on this amazing plugin!

**Comment by mProjectsCode** [comment] 2024-04-06 22:05
duplicate of https://github.com/mProjectsCode/obsidian-meta-bind-plugin/discussions/256

**Comment by mProjectsCode** [comment] 2024-04-06 22:06
The templater API which the plugin is using does not expose more options

**Closed** 2024-04-06 22:06 UTC
Labels: duplicate, feature request
