### ISSUE TITLE
Button `insertIntoNote` below button

### ISSUE THREAD

**Issue by Tejeev** [mProjectsCode/obsidian-meta-bind-plugin#345] opened 2024-06-05 07:58 UTC
### Is your Feature Request Related to a Problem?

I can't use an `insertIntoNote` button in a dynamic document because line numbers change

### Describe the Feature you'd Like

Insert templates in a new line below the button

**Comment by mProjectsCode** [comment] 2024-06-05 09:53
duplicate of #296

**Closed** 2024-06-05 09:53 UTC
Labels: feature request

**Comment by Tejeev** [comment] 2024-06-05 09:59
Sorry, I missed that issue.
Thank you!
