### ISSUE TITLE
Plugin causes crashes on iOS

### ISSUE THREAD

**Issue by Pachtjuilaard** [mProjectsCode/obsidian-meta-bind-plugin#102] opened 2023-06-21 14:44 UTC
-   [x] The Plugin is up to date
-   [x] Obsidian is up to date

**Describe the bug**
Upon loading a note that contains a meta bind field, the app crashes. If the mobile app restarts and loads that same note again, the app freezes before loading. This forces me to change the name of the .md file in iOS files, as Obsidian can not be loaded before the note with the meta bind field is deleted or renamed.

**To Reproduce**

1. Write some meta bind field on a note: `INPUT[text:test]`
2. Close the note, and reopen it.
3. Obsidian crashes. 
4. If Obsidian reloads that note (doesn't always do that), the app freezes before loading. This makes changing the note in Obsidian impossible.

**Expected behavior**
To not crash?

**Screenshots**

**Occurs on**
iOS, iPadOS

**Plugin version**
Any version since 0.4.0

**Additional context**

**Comment by mProjectsCode** [comment] 2023-06-23 07:17
I can't reproduce this on my android phone. 
Do you have any other plugins active?

**Comment by careilly** [comment] 2023-08-04 14:15
Same problem here, with a clean vault with only this plugin and a single file. Current iOS Testflight.

**Comment by careilly** [comment] 2023-08-04 22:29
On further investigation, it’s not crashing on iPad, but is taking long pauses, and “this tab is currently busy” messages and becoming unresponsive. I’ll try the “disable plugins one by one” game tomorrow.

**Comment by careilly** [comment] 2023-08-04 23:50
Just started the process by turning them all off and it crashed immediately.

**Comment by mProjectsCode** [comment] 2023-08-05 09:16
So turning off all plugins crashes it instantly? Then it doesn't seem to be an issue with the plugin but Obsidian, no?

**Comment by careilly** [comment] 2023-08-05 09:19
No, I mean even with all plugins turned off except meta-bind it crashes on phone, locks up on iPad.

**Comment by mProjectsCode** [comment] 2023-08-05 09:28
Strange. I still can't repo it on my Android phone and I don't own any Apple device, so I can't test it myself.

Could you send me the Vault that crashes as a zip file? 
Is it possible to open the developer console on an apple device? If so, could you also send me the contents of the console?

**Comment by careilly** [comment] 2023-08-05 09:33
Let me have a look at reliably replicating it with a fresh vault - can’t send my main one! - and checking what happens with the release app. I’ll get what logs I can, but no console on iOS. It’ll be a few days. On 5 Aug 2023, at 10:28, Moritz Jung ***@***.***> wrote:﻿
Strange. I still can't repo it on my Android phone and I don't own any Apple device, so I can't test it myself.
Could you send me the Vault that crashes as a zip file?
Is it possible to open the developer console on an apple device? If so, could you also send me the contents of the console?

**Comment by mProjectsCode** [comment] 2023-11-15 20:35
i am closing this due to inactivity

**Comment by claremacrae** [comment] 2023-12-07 15:10
I believe I may have seen this. I will report back when I have been able to get a reproduction.

**Comment by claremacrae** [comment] 2023-12-11 17:00
> I believe I may have seen this. I will report back when I have been able to get a reproduction.

**Summary: I cannot reproduce the crash when meta-bind is the only plugin enabled.**

1. I emptied out my test vault and installed only meta-bind
2. I added this file, which is pretty much what crashed previously.

[MetaBind Examples.md](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/files/13638676/MetaBind.Examples.md)

3. I then turned on syncing of absolutely everything in the vault
4. And loaded the vault on iPhone
5. And could edit the metadata via all the widgets, absolutely fine.

Debug info for this setup:

[Debug Info on iPhone - only Meta Bind.md](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/files/13638713/Debug.Info.on.iPhone.-.only.Meta.Bind.md)

**Comment by claremacrae** [comment] 2023-12-11 17:05
1. I then copied all plugin folders from my main vault, in to this test vault.
2. Then copied in the `community-plugins.json`
3. Waited for sync to complete on desktop then mobile
4. Restarted Obsidian on iPhone

**And I was able to edit properties file, absolutely no problem.**

**Comment by claremacrae** [comment] 2023-12-11 17:13
So I went back to my main vault and did the following:

1. Re-enabled Meta Bind
2. Opened the above note (well, the same table, but it has a bit more descriptive text)
3. It showed the raw markdown in Reading - couldn't get it to display the widgets
4. Force-quit Obsidian and restarted
5. Instead of showing the rendered widgets, Obsidian crashed
6. Restarted Obsidian (or maybe it restarted itself, I cannot remember)
7. Unlike when I first tried this 4 days ago, after the (second) restart, the Meta Bind widgets were displayed correctly.

**Summary: So it did crash again, but after 2 restarts it was fine.**

**Comment by claremacrae** [comment] 2023-12-11 17:16
Here is the debug info for the vault in my previous message:

[Debug Info on iPhone - all plugins - my main vault.md](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/files/13638828/Debug.Info.on.iPhone.-.all.plugins.-.my.main.vault.md)

**Comment by careilly** [comment] 2023-12-11 17:17
I’m guessing it’s a resource exhaustion problem, like a lot of iOS crashes seem to be - stuff crashes on my iPhone that doesn’t crash on my much more powerful iPad. 

Regards,

Colman

**Comment by mProjectsCode** [comment] 2023-12-11 17:25
So I am guessing it is a memory limitation with lots of other active plugins.
Idk if there is anything that i can do about that.

**Comment by careilly** [comment] 2023-12-11 17:37
Yeah, the iOS wrapper looks to be bad at handling memory - it may be Metabind is leaking somewhere, I suppose, but I’m not sure how you’d fix that either, since JS should be sorting that out for you.

Regards

Colman

**Comment by mProjectsCode** [comment] 2023-12-11 23:01
It seems like in the desktop app it takes around 45 MB of memory to load the plugin thanks to Mathjs. In comparison, base obsidian uses around 30 MB.

**Comment by mProjectsCode** [comment] 2023-12-11 23:05
So I have two options. Either I ignore the issue or I write my own version of a math string evaluator that is more lightweight. But that might break existing notes as i won't be able to replicate all math js features.

**Comment by claremacrae** [comment] 2023-12-11 23:09
A wild guess. If you are not using all of mathjs, might it be possible to have your own cut-down build of it?

Also, how confident are you that memory is the issue? 45MB doesn't sound that huge to me, naively.

**Comment by mProjectsCode** [comment] 2023-12-11 23:11
From the other issue, it sounds like it is a startup issue aka when the plugin loads. And it tracks with the other things, e.g. it crashes for you only with lots of other plugins enabled.

**Comment by careilly** [comment] 2023-12-11 23:19
I’d say document that it doesn’t work well on iOS and raise an issue with the Obsidian developers. Thats not that much memory in modern terms and it shouldn’t crash like that. (Though if anyone wants stories about developing in 1k on a ZX81 I can provide.)Would disabling math in view fields on iOS help? As a config option maybe? On 11 Dec 2023, at 23:05, Moritz Jung ***@***.***> wrote:﻿
So I have two options. Either I ignore the issue or I write my own version of a math string evaluator that is more lightweight. But that might break existing notes as i won't be able to replicate all math js features.

**Comment by mProjectsCode** [comment] 2023-12-11 23:20
> Would disabling math in view fields on iOS help? As a config option maybe?

No, as it allocates all the memory when the module gets loaded.

**Comment by mProjectsCode** [comment] 2023-12-11 23:23
Just checked, mathjs also makes up half the bundle size of the plugin.

**Comment by claremacrae** [comment] 2023-12-12 06:28
> Bundle size visualization if anyone is interested.

Wow, it's off-topic, but how did you create that visualisation please?

**Comment by claremacrae** [comment] 2023-12-12 06:40
> > Bundle size visualization if anyone is interested.
> 
> Wow, it's off-topic, but how did you create that visualisation please?

Found it:
https://esbuild.github.io/analyze/

**Comment by mProjectsCode** [comment] 2023-12-12 10:42
@careilly @claremacrae 

I just published a new beta release available through BRAT that removes mathjs as a dependency. Could you try and see if you can still reproduce the issue with that build?

**Comment by claremacrae** [comment] 2023-12-12 11:34
Sorry, I'm not going to be able to do that until Friday at the earliest.

**Comment by claremacrae** [comment] 2023-12-12 16:27
> Sorry, I'm not going to be able to do that until Friday at the earliest.

Change of plan. Obsidian started freezing at launch on my iPhone, instead of crashing.
So I:

1. Went in to Working Copy on the phone and deleted Meta Bind from the list of enabled plugins
2. On my Mac, enabled and updated BRAT
3. Added this plugin to BRAT
4. It installed:

```json
{
    "id": "obsidian-meta-bind-plugin",
    "name": "Meta Bind Plugin",
    "version": "0.9.0-canary.20231212T104031",
    "minAppVersion": "1.4.0",
    "description": "This plugin can create input fields inside your notes and bind them to metadata fields.",
    "author": "Moritz Jung",
    "authorUrl": "https://mprojectscode.github.io/",
    "helpUrl": "https://www.moritzjung.dev/obsidian-meta-bind-plugin-docs/",
    "isDesktopOnly": false
}
```

5. Let that sync to iPhone
6. Restarted Obsidian on iPhone
7. Enabled Meta Bind on iPhone
8. Restarted Obsidian on iPhone
9. **Sorry to report that I am getting similar behaviour - sometimes Obsidian opens and restarts - sometimes I get a black screen**

**Comment by claremacrae** [comment] 2023-12-12 16:28
I know that Meta Bind did start, as Working Copy shows a diff in the plugin's settings, that `enableSyntaxHighlighting` is added and enabled.

**Comment by claremacrae** [comment] 2023-12-12 16:29
(Oh - maybe that got synced from Mac???)

**Comment by claremacrae** [comment] 2023-12-12 16:35
On the iPhone I:

- Disabled all plugins
- Installed [Logstravaganza](https://github.com/czottmann/obsidian-logstravaganza)
- Enabled the beta of Meta Bind
- Restarted Obsidian
- Opened my test Meta Bind note
- Toggled one or two toggles
- **Obsidian restarted**

Here is the log - it's not useful:

[LOGGING-NOTE (iPhone).md](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/files/13650780/LOGGING-NOTE.iPhone.md)

**Comment by mProjectsCode** [comment] 2023-12-12 18:31
Hmm, that rules out mathjs.
I tried with your note and i can't at all reproduce the bug on my android phone.

> Here is the log - it's not useful:

It's strange to me that there are no `console.debug` recorded, as the plugin uses many of those.

**Comment by claremacrae** [comment] 2023-12-12 19:46
I feel at this point I should offer to learn how to debug plugins on my iPhone, from my Mac... The problem is that I first need to update the Mac OS two versions...

So... it's not something that's going to happen immediately.

I wonder if there are Mac/iPhone Meta Bind users in #plugin-dev on Discord that might be able to spare some time to help the plugin out with a debugging session?

**Comment by mProjectsCode** [comment] 2023-12-13 18:16
Are all of you who are experiencing this issue using Obsidian Sync?

**Comment by claremacrae** [comment] 2023-12-13 18:49
> Are all of you who are experiencing this issue using Obsidian Sync?

I am.

> When did you first install obsidian? (before or after the iOS 17.0 upgrade)

About 18 months or 2 years ago.

> Does a complete reinstall of obsidian (**back up vault data first**) help?

Sorry, I don't have the time to do that.

**Comment by mProjectsCode** [comment] 2023-12-13 19:02
ok. This more or less confirms it. It seems to be an iOS/webkit bug that is affecting Obsidian Sync and possibly the entirety of Obsidian (confirmed by Sigrunixia). Big plugins like Meta Bind and Dataview seem to make the issue appear more frequently.

That means I can't do anything bout this bug. This is on the Obsidian devs (they are working on it) and webkit devs to fix.

[Here](https://bugs.webkit.org/show_bug.cgi?id=264099#c3) is a related bug report on the webkit bug tracker. 
[Here](https://github.com/firebase/firebase-js-sdk/issues/7742) is a related issue with firebase.

**Comment by claremacrae** [comment] 2023-12-13 19:11
Do I infer from the second issue that if I were to re-install Obsidian the issue would be fixed on my device?

**Comment by careilly** [comment] 2023-12-13 20:23
Lots of console logs from WebKit when I started to look earlier. I’d say stick a warning on the documentation and link to this issue. Not much else you can do … I’m reinstalling obsidian and syncing now to see what happens. I’ll report back if it makes a difference.On 13 Dec 2023, at 19:18, Moritz Jung ***@***.***> wrote:﻿
According to Sigrunixia, the issue does not occur if obsidian was installed after the iOS 17.0 update. But I can't confirm that.

**Comment by careilly** [comment] 2023-12-13 21:58
I can cautiously report that a fresh install of Obsidian on my iPhone is working much better than previously, allowing me to cut and paste examples from the test vault without crashing immediately.

**Comment by claremacrae** [comment] 2023-12-14 08:37
> According to Sigrunixia, the issue does not occur if obsidian was installed after the iOS 17.0 update. But I can't confirm that.

I think I'm missing something here... I have 50 or more plugins that are working fine on the same iPhone.

So what is it about this plugin which means it's affected by the iOS 17.0 update when most others are not?

**Comment by mProjectsCode** [comment] 2023-12-14 09:45
> So what is it about this plugin which means it's affected by the iOS 17.0 update when most others are not?

Short answer: I don't know.

Long answer: 
Since I didn't know what else to do, I contacted the Obsidian team (Sigrunixia) and she took a look at the two bug reports. According to her, this issue looks like a known bug in Obsidian Sync / base Obsidian that the Obsidian devs are already working on fixing. As far as I can tell the bug affects Obsidian indexing and is caused by an iOS/webkit bug that messes with apps trying to delete data.
As to why this plugin makes the issue appear more frequently, I don't know. However, the Obsidian devs are aware that some plugins make this issue appear more frequently. 

Sigrunixia made a [support post](https://discord.com/channels/925322340995313686/1184580029879947465) for the issue on the Obsidian TTRPG discord server.
I am not aware of a forum post for this.

**Comment by claremacrae** [comment] 2023-12-14 09:53
Thank you for the reply - much appreciated.

(I'm not on the TTRPG Discord server so can't read that post.)

**Comment by careilly** [comment] 2023-12-14 10:26
I can report that after the complete reinstall on iOS 17.2 I can so far do stuff with MetaBind that I would have expected to make the app completely unusable on iPhone - and changing a linked slider in a note on my iPhone now updates my desktop inside a couple of seconds. So it's certainly improved matters for me.

**Comment by careilly** [comment] 2023-12-14 10:33
A test note with 200 toggles - half linked to another note -  and some of the example code is performing perfectly now. I'll do the same process on my iPad and see how that goes - on the iPad it was more causing massive slowdowns than complete crashes.

**Comment by careilly** [comment] 2023-12-20 14:53
I'm not having any problems caused by meta bind now - though I haven't extensively used it yet - but on both iPhone and iPad with up to date operating systems a delete, reinstall and sync has stopped it crashing/locking up.

**Comment by scarfur** [comment] 2023-12-26 15:09
I can reproduce even after reinstalling obsidian on iOS 17 😢(had it installed since 2y +). It crashes and restarts only when I open the test note. Test note has 191 `INPUT` fields (some of them are `suggester`s with 50 `options`), 73 `sliders`, 378 dataview inline `choice()`s and 627 dataview inline fields (`=this` or simply `this` when nested).
I first thought it is a simple overload but after deleting bigger blocks of content and only with some `INPUT numbers` left -> same behaviour. Really sad. Can not test with sync - not using it atm.

**Comment by mProjectsCode** [comment] 2023-12-26 15:40
Does the issue still occur with only dataview and only meta bind?

**Comment by scarfur** [comment] 2023-12-26 15:41
> Does the issue still occur with only dataview and only meta bind?

had the same mindflow and still creating that situation by changing the files. gonna edit soon

**Comment by mProjectsCode** [comment] 2023-12-26 15:51
what about only meta bind and no other plugins?
And can you send me your file if possible?

**Comment by scarfur** [comment] 2023-12-26 16:00
> what about only meta bind and no other plugins? And can you send me your file if possible?

sorry that answer do not came on the same edit, the whole crashing and slow start times on iOS, slowing the whole testing down...
**The same crash behaviour as before with meta bind ON and dataview OFF.**
I am testing now with only meta bind and all other plugins off but I expect no change. Do not have that much enabled on that vault but for clarity I'm still curious to see if anything changes

**Comment by mProjectsCode** [comment] 2023-12-26 16:21
what iOS version are you using?
You might be running into iOS memory limitations.

**Comment by scarfur** [comment] 2023-12-26 16:35
> what iOS version are you using? You might be running into iOS memory limitations.

Latest version, 17.2.1, that could be true. Tested with meta plugin as the only plugin activated and still crashes.

**Comment by careilly** [comment] 2023-12-26 17:54
When you reinstalled, did you use a clean vault? My delete/reinstall was using sync so it zapped the whole vault.Colman On 26 Dec 2023, at 16:35, scarfur ***@***.***> wrote:﻿

what iOS version are you using? You might be running into iOS memory limitations.

Latest version, 17.2.1, that could be true. Tested with meta plugin as the only plugin activated and still crashes.

**Comment by scarfur** [comment] 2023-12-26 19:16
> When you reinstalled, did you use a clean vault? My delete/reinstall was using sync so it zapped the whole vault.Colman On 26 Dec 2023, at 16:35, scarfur ***@***.***> wrote:﻿ what iOS version are you using? You might be running into iOS memory limitations. Latest version, 17.2.1, that could be true. Tested with meta plugin as the only plugin activated and still crashes. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

Nope just the app got deleted but thanks for warning everyone

**Comment by careilly** [comment] 2023-12-26 19:37
So did any previously created indexes etc <waves hands> get deleted? Colman On 26 Dec 2023, at 19:16, scarfur ***@***.***> wrote:﻿

When you reinstalled, did you use a clean vault? My delete/reinstall was using sync so it zapped the whole vault.Colman On 26 Dec 2023, at 16:35, scarfur @.> wrote:﻿ what iOS version are you using? You might be running into iOS memory limitations. Latest version, 17.2.1, that could be true. Tested with meta plugin as the only plugin activated and still crashes. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: @.>

Nope just the app got deleted but thanks for warning everyone

**Comment by scarfur** [comment] 2023-12-26 20:51
> So did any previously created indexes etc <waves hands> get deleted? 

Obsidian indexed the files again yes ;)

**Comment by the1gofer** [comment] 2024-01-20 20:55
I am having the issue when activating the metabind plugin. On both iOS and android.  Any word on a fix?

**Comment by mProjectsCode** [comment] 2024-02-24 20:53
Does the issue still occur on the latest iOS, obsidian, and plugin versions?

**Comment by AniOhev** [comment] 2024-02-27 13:42
No recent crashes iOS 1.5.8

**Comment by mProjectsCode** [comment] 2024-03-07 23:47
I will close this issue for now, as it seems to have fixed itself. I will reopen this if the issue reappears.

**Closed by mProjectsCode** 2024-03-07 23:47 UTC
Labels: bug, upstream bug
