### ISSUE TITLE
Make date picker float on top

### ISSUE THREAD

**Issue by phlind** [mProjectsCode/obsidian-meta-bind-plugin#19] opened 2022-10-09 16:30 UTC
- [x] The Plugin is up to date
- [x] Obsidian is up to date

I use Admonitions with a smaller width and would like to integrate the date picker field into them. Unfortunately, the date picker does not hover on top of the Admonition, but is located inside of it. Therefore it's cut off. Could the date picker made to float on top always?

**Expected behavior**

**Screenshots**
![plugin](https://user-images.githubusercontent.com/30386310/194768305-11f4a3f0-4045-483f-be6d-38bdd0ebf87f.PNG)

**Occurs on**
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Plugin version**
0.2.1

**Comment by mProjectsCode** [comment] 2022-10-09 16:41
Oops, i know the cause, will fix tomorrow

**Comment by mProjectsCode** [comment] 2022-10-09 16:41
But hey the date picker works in light mode, didn't expect that

**Comment by phlind** [comment] 2022-10-09 16:42
Nice, thank you! :) Yes, it works well in light and dark mode.

**Comment by mProjectsCode** [comment] 2022-10-10 10:41
This is a bit more complicated than I thought, but for now, I just added a new argument that can be added to the date picker called `alignRight` which will align the date picker with the right side of the input field

**Comment by mProjectsCode** [comment] 2022-10-11 10:10
the temp fix is included in v0.3.0

**Comment by phlind** [comment] 2022-10-16 10:21
Hey, I just tried version 0.3.0. Now there is the following problem: Since in my example the date picker is in a table, it doesn't actually show the picker now. It's basically hidden in the table cell.

**Comment by mProjectsCode** [comment] 2022-10-16 10:23
hmm, seems like i cant rest easy on my temp fix after all xD

**Comment by phlind** [comment] 2022-10-16 10:24
Unfortunately not, it seems. ;) Here you can quickly try yourself:

```
| Test |                           |
| ---- | ------------------------- |
| Date | `INPUT[date_picker:date]` | 
```

**Comment by mProjectsCode** [comment] 2022-10-16 10:26
yeah it's because the data picker in the element tree is part of the input field and things like the table cell cut off overflow,

**Comment by mProjectsCode** [comment] 2022-12-02 13:40
![image](https://user-images.githubusercontent.com/61602848/205305525-9e7c9d19-a74a-40ec-96de-5e0e7b15b151.png)
i made the date picker into a modal and made it's style a bit more compatible with obsidian 1.0

**Closed** 2022-12-02 16:10 UTC
Labels: bug
